export const STOPS = {
  footprints: {
    id: 'footprints',
    number: 1,
    title: 'The Footprint Trail',
    area: 'Major area 1',
    description: 'Animated detective footprints cross the floor and lead visitors onward.',
    tracking: 'image',
    surface: 'floor',
    targetName: 'footprints-qr',
    targetData: '/image-targets/footprints-qr.json',
    qrSizeMeters: 0.12,
    placementMode: 'shelf-to-ground',
    groundOffsetY: 0.9,
    floorLift: 0.02,
    trailForward: 0.4,
    effect: 'footprints',
    placementDistance: 1.4,
    placementHeight: 0.03,
    modelSrc: null,
    animationClip: null,
  },
  bus: {
    id: 'bus',
    number: 2,
    title: 'The Flying Magic Bus',
    area: 'Major area 2',
    description: 'The bus fades in on the printed QR, flies across, then fades out on the other side.',
    tracking: 'image',
    surface: 'wall',
    targetName: 'bus-qr',
    qrSizeMeters: 0.12,
    effect: 'bus',
    placementDistance: 0,
    placementHeight: 0,
    modelSrc: '/assets/models/magic_bus.glb',
    modelSize: 1.6,
    modelRotation: '0 -90 0',
    motion: 'fly-horizontal',
    animationClip: null,
  },
  painting: {
    id: 'painting',
    number: 3,
    title: 'The Growing Painting',
    area: 'Major area 3',
    description: 'Scan the QR beside the painting. Ivy grows from behind the four edges of the frame.',
    tracking: 'image',
    targetName: 'painting-qr',
    targetData: '/image-targets/painting-qr.json',
    qrSizeMeters: 0.12,
    effect: 'plant',
    placementDistance: 1.7,
    placementHeight: 1.25,
    modelSrc: null,
    animationClip: null,
  },
  colors: {
    id: 'colors',
    number: 4,
    title: 'The Color Box',
    area: 'Major area 4',
    description: 'Animated rainbow color shooting out from the printed QR toward the visitor.',
    tracking: 'image',
    targetName: 'colors-qr',
    targetData: '/image-targets/colors-qr.json',
    qrSizeMeters: 0.12,
    effect: 'colors',
    placementDistance: 1.4,
    placementHeight: 0.8,
    modelSrc: null,
    animationClip: null,
  },
  caterpillar: {
    id: 'caterpillar',
    number: 5,
    title: 'The Climbing Caterpillar',
    area: 'Major area 5',
    description: 'The caterpillar appears on the printed QR and crawls upward from there.',
    tracking: 'image',
    surface: 'vertical',
    targetName: 'caterpillar-qr',
    targetData: '/image-targets/caterpillar-qr.json',
    qrSizeMeters: 0.12,
    effect: 'caterpillar',
    placementDistance: 0,
    placementHeight: -0.35,
    modelSrc: '/assets/models/catterpillarG.glb',
    modelSize: 0.15,
    modelRotation: '0 180 90',
    motion: 'climb-vertical',
    animationClip: 'Armature|Crawling',
  },
  naruto: {
    id: 'naruto',
    number: 6,
    title: 'The Ninja Reveal',
    area: 'Major area 6',
    description: 'Scanning the QR code reveals an animated ninja entrance.',
    tracking: 'image',
    surface: 'floor',
    targetName: 'naruto-qr',
    targetData: '/image-targets/naruto-qr.json',
    qrSizeMeters: 0.12,
    effect: 'ninja',
    placementDistance: 0,
    placementHeight: 0,
    modelSrc: '/assets/models/naruto.glb',
    modelSize: 0.0003,
    modelRotation: '0 0 0',
    motion: 'reveal',
    animationClip: 'Armature|mixamo.com|Layer0',
  },
}

export const STOP_LIST = Object.values(STOPS).sort((a, b) => a.number - b.number)

export function getStopFromLocation(location = window.location) {
  const stopId = new URLSearchParams(location.search).get('stop')?.toLowerCase()
  return stopId ? STOPS[stopId] ?? null : null
}

export function getStopUrl(stop, base = window.location.href) {
  const url = new URL('/ar.html', base)
  url.searchParams.set('stop', stop.id)
  return url.toString()
}
